package it.polimi.ingsw.view.Gui.SceneControllers.ptPositions;
/**
 * Enum representing various distances used in GUI positioning in PointTable for each point in the point table.
 */
public enum PTPOSITION {

    PT0(DISTANCE.COULUMN1.data,DISTANCE.LINE0.data),
    PT1(DISTANCE.COULUMN1.data+DISTANCE.DISTANCEC.data,DISTANCE.LINE0.data),
    PT2(DISTANCE.COULUMN1.data+DISTANCE.DISTANCEC.data*2,DISTANCE.LINE0.data),
    PT3(DISTANCE.COULUMN0.data+DISTANCE.DISTANCEC.data*3,DISTANCE.LINE0.data-DISTANCE.DISTANCEL.data),
    PT4(DISTANCE.COULUMN0.data+DISTANCE.DISTANCEC.data*2,DISTANCE.LINE0.data-DISTANCE.DISTANCEL.data),
    PT5(DISTANCE.COULUMN0.data+DISTANCE.DISTANCEC.data*1,DISTANCE.LINE0.data-DISTANCE.DISTANCEL.data),
    PT6(DISTANCE.COULUMN0.data,DISTANCE.LINE0.data-DISTANCE.DISTANCEL.data),
    PT7(DISTANCE.COULUMN0.data+DISTANCE.DISTANCEC.data*0,DISTANCE.LINE0.data-DISTANCE.DISTANCEL.data*2),
    PT8(DISTANCE.COULUMN0.data+DISTANCE.DISTANCEC.data*1,DISTANCE.LINE0.data-DISTANCE.DISTANCEL.data*2),
    PT9(DISTANCE.COULUMN0.data+DISTANCE.DISTANCEC.data*2,DISTANCE.LINE0.data-DISTANCE.DISTANCEL.data*2),
    PT10(DISTANCE.COULUMN0.data+DISTANCE.DISTANCEC.data*3,DISTANCE.LINE0.data-DISTANCE.DISTANCEL.data*2),
    PT11(DISTANCE.COULUMN0.data+DISTANCE.DISTANCEC.data*3,DISTANCE.LINE0.data-DISTANCE.DISTANCEL.data*3),
    PT12(DISTANCE.COULUMN0.data+DISTANCE.DISTANCEC.data*2,DISTANCE.LINE0.data-DISTANCE.DISTANCEL.data*3),
    PT13(DISTANCE.COULUMN0.data+DISTANCE.DISTANCEC.data*1,DISTANCE.LINE0.data-DISTANCE.DISTANCEL.data*3),
    PT14(DISTANCE.COULUMN0.data+DISTANCE.DISTANCEC.data*0,DISTANCE.LINE0.data-DISTANCE.DISTANCEL.data*3),
    PT15(DISTANCE.COULUMN0.data+DISTANCE.DISTANCEC.data*0,DISTANCE.LINE0.data-DISTANCE.DISTANCEL.data*4),
    PT16(DISTANCE.COULUMN0.data+DISTANCE.DISTANCEC.data*1,DISTANCE.LINE0.data-DISTANCE.DISTANCEL.data*4),
    PT17(DISTANCE.COULUMN0.data+DISTANCE.DISTANCEC.data*2,DISTANCE.LINE0.data-DISTANCE.DISTANCEL.data*4),
    PT18(DISTANCE.COULUMN0.data+DISTANCE.DISTANCEC.data*3,DISTANCE.LINE0.data-DISTANCE.DISTANCEL.data*4),
    PT19(DISTANCE.COULUMN0.data+DISTANCE.DISTANCEC.data*3,DISTANCE.LINE0.data-DISTANCE.DISTANCEL.data*5),
    PT20(DISTANCE.COULUMN0.data+DISTANCE.DISTANCEC.data*1.5,DISTANCE.LINE0.data-DISTANCE.DISTANCEL.data*5.5),
    PT21(DISTANCE.COULUMN0.data+DISTANCE.DISTANCEC.data*0,DISTANCE.LINE0.data-DISTANCE.DISTANCEL.data*5),
    PT22(DISTANCE.COULUMN0.data+DISTANCE.DISTANCEC.data*0,DISTANCE.LINE0.data-DISTANCE.DISTANCEL.data*6),
    PT23(DISTANCE.COULUMN0.data+DISTANCE.DISTANCEC.data*0,DISTANCE.LINE0.data-DISTANCE.DISTANCEL.data*7),
    PT24(DISTANCE.COULUMN0.data+DISTANCE.DISTANCEC.data*0.5,DISTANCE.LINE0.data-DISTANCE.DISTANCEL.data*8),
    PT25(DISTANCE.COULUMN0.data+DISTANCE.DISTANCEC.data*1.5,DISTANCE.LINE0.data-DISTANCE.DISTANCEL.data*8),
    PT26(DISTANCE.COULUMN0.data+DISTANCE.DISTANCEC.data*2.5,DISTANCE.LINE0.data-DISTANCE.DISTANCEL.data*8),
    PT27(DISTANCE.COULUMN0.data+DISTANCE.DISTANCEC.data*3,DISTANCE.LINE0.data-DISTANCE.DISTANCEL.data*7),
    PT28(DISTANCE.COULUMN0.data+DISTANCE.DISTANCEC.data*3,DISTANCE.LINE0.data-DISTANCE.DISTANCEL.data*6),
    PT29(DISTANCE.COULUMN0.data+DISTANCE.DISTANCEC.data*1.5,DISTANCE.LINE0.data-DISTANCE.DISTANCEL.data*6.7);

    public final double x;
    public final double y;
    PTPOSITION(double x, double y) {
        this.x=x;
        this.y=y;
    }
}
